language: python
python: 3.6
sudo: false
install: "pip install -r maintenance/requirements.txt"
script: "python maintenance/github-crawler.py"
deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis/push.sh
  skip_cleanup: true
  on:
    branch: master
